import type { Metadata } from 'next'
import { Be_Vietnam_Pro } from 'next/font/google'
import './globals.css'
import { Hero } from '@/components'

const BeVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ['600', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
})
{
  return (
    <html lang="en">
      <body className={`${BeVietnamPro.className} bg-background text-primary`}>
        <Hero />
        {children}
      </body>
    </html>
  )
}
